---

- name: Add node.js repository
  apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu lucid main' state=present update-cache=yes
  when: ansible_distribution == 'Debian'

- name: Install nodejs and npm
  apt: pkg=nodejs state=latest force=yes

- name: Install npm packages global
  shell: npm install -g {{npm_global_packages | join(" ")}}
