---
- include: php-cli.yml
- include: php-fpm.yml

- name: Install php5 extensions
  apt: pkg={{ item }} state=installed
  with_flattened:
    - php_mandatory_extensions
    - php_extensions
  notify: restart php-fpm

- include: pecl.yml