---
- name: Install PECL dependencies
  apt: pkg={{ item }} state=installed
  when: ansible_os_family == "Debian" and php_pecl_extensions|length > 0
  with_items: php_pear_packages
  tags: [packages,php]

- name: Install PECL extensions
  shell: echo "\n\n\n\n\n\n\n\n\n\n" | pecl install {{ item.name }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: php_pecl_extensions
  tags: [packages,php]

- name: Create PECL extensions .ini files
  template: src={{ item.ini | default("extension.ini.j2") }} dest=/etc/php5/mods-available/{{ item.name }}.ini owner=root group=root mode=0644
  with_items: php_pecl_extensions
  when: ansible_os_family == "Debian"
  tags: [packages,php]

- name: Enable PECL extensions
  shell: php5enmod  {{ item.name }}
  with_items: php_pecl_extensions
  when: ansible_os_family == "Debian"
  tags: [packages,php]
